### ISSUE TITLE
[FEAT] 커뮤니티 스크린의 세부 개발을 진행합니다.

### ISSUE THREAD

**Issue by sy5072** [widin-official/Widin#1]
## 💡 Issue

커뮤니티 스크린의 세부 사항 개발을 진행합니다.

## 📝  todo
- [x] 답글 스크린 생성
- [x] 답글 정렬 순서 변경
- [x] 답글 삭제 버튼, 얼럿 추가
- [x] 이중 스크롤 차단
- [x] 배경 색상 변경 

## 추후 구현 리스트
- 본인 댓글/답글 구분
